version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:05"
      timezone: Europe/Berlin
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-name: "@sentry/nextjs"
      - dependency-name: "eslint"
      - dependency-name: "next"
    ignore:
      - dependency-name: "*"
        dependency-type: "all"
