version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:55"
      timezone: Europe/Berlin
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-is"
