version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:50"
      timezone: "UTC"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
    allow:
      - dependency-name: "styled-components"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
