name: Dependabot Auto-Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
