name: Vercel Scheduled Build

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1" # At 03:30 UTC every Monday

jobs:
  consumer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger Vercel deploy hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
